version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/payment-composer-ui"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/payment-composer-api"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/payment-router"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/orchestrator"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
