version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: moneyflow
      POSTGRES_DB: moneyflow
    ports:
      - 5433:5432
    restart: unless-stopped
    volumes:
      - database_volume:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  payment-composer-api:
    build:
      context: payment-composer-api
      target: development
    command: ["wait-for", "postgres:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    depends_on:
      - postgres
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ./payment-composer-api:/app

  payment-composer-ui:
    build:
      context: payment-composer-ui
      target: development
    depends_on:
      - payment-composer-api
    ports:
      - 5173:5173
    restart: unless-stopped
    volumes:
      - ./payment-composer-ui:/app
      - /app/node_modules

  payment-router:
    build:
      context: payment-router
      target: development
    command: ["wait-for", "payment-composer-api:80", "rabbitmq:5672", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    depends_on:
      - rabbitmq
    environment:
      - PAYMENT_COMPOSER_API=http://payment-composer-api:80
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq:5672
    ports:
      - 8001:80
    restart: unless-stopped
    volumes:
      - ./payment-router:/app

  orchestrator:
    build:
      context: orchestrator
      target: development
    command: ["wait-for", "rabbitmq:5672", "--", "python", "-m", "app.main"]
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq:5672
    restart: unless-stopped
    volumes:
      - ./orchestrator:/app

volumes:
  database_volume:
