name: Tests

on:
  push:
    branches:
      - main

jobs:
  payment-composer-api-unit-test:
    name: Payment Composer API Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: payment-composer-api
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: moneyflow
          POSTGRES_PASSWORD: moneyflow
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
          cache-dependency-path: "payment-composer-api/poetry.lock"

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        env:
          POSTGRES_DSN: "postgresql+asyncpg://postgres:moneyflow@localhost:5432/test_db"
        run: |
          export PYTHONPATH=$(pwd)
          poetry run pytest -vv -s
